force-app/main/default/objects/Ball_Pool__c/Ball_Pool__c.object-meta.xml
<CustomObject>
    <label>Ball Pool</label>
    <nameField>
        <label>Ball Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ball Pool</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ball_Pool__c/fields/Ball_Number__c.field-meta.xml
<CustomField>
    <fullName>Ball_Number__c</fullName>
    <label>Ball Number</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ball_Pool__c/recordTypes/OZ_Lotto.recordType-meta.xml
<RecordType>
    <fullName>OZ_Lotto</fullName>
    <active>true</active>
    <label>OZ Lotto</label>
</RecordType>

force-app/main/default/classes/BallPoolController.cls
public with sharing class BallPoolController {

    static Id ozLottoRecTypeId;

    @AuraEnabled(cacheable=true)
    public static List<Ball_Pool__c> getOZLottoBallList() {
        getRecordTypeIds();

        List<Ball_Pool__c> ozLottoBalls = new List<Ball_Pool__c>();
        ozLottoBalls = [SELECT Id, Name, Ball_Number__c FROM Ball_Pool__c WHERE RecordTypeId =: ozLottoRecTypeId ORDER BY Ball_Number__c];

        return ozLottoBalls;
    }


    static void getRecordTypeIds() {

        Map<String,Schema.RecordTypeInfo> recTypeMapByDevNameBallPool = Schema.SObjectType.Ball_Pool__c.getRecordTypeInfosByDeveloperName();
       
        ozLottoRecTypeId = recTypeMapByDevNameBallPool.get('OZ_Lotto').getRecordTypeId();
    }

}